### ISSUE TITLE
RPG Items (Food)

### ISSUE THREAD

**Issue by Valarith** [TheCreeperOfRedstone/RPG-Items-2#7]
Hello there,i got a new cool idea on RPG Items and i believe it gonna be very on RPG Items.
The main think i wan't to be added is RPG Items food what exactly will be this:

●RPG Items that when get eaten gonna be removed,and give a custom reward to the player that eats them.

This RPG Items food should have these powers:
- Command (Only right click here if it's possible)
- Potionself
- Food

Hope, you like my ideas,and add them one day on the plugin.
Thank you for your hardwork updating the amazing plugin RPG Items.

**Comment by michalet** [comment]
I believe you can already do this. Just add the consume power (to remove the item on rclick) to the other commands. (Yep, it's not exactly the same as eating it, but very similar.)

**Comment by Valarith** [comment]
Thank you,It works nice!I has no idea what consume power does since the power does not have description. :D Also I can make reward bags now.
